export enum GameTabType {
	HOME = "YOUR HOUSE",
	LETTERS = "LETTERS",
	SHOP = "SHOP",
	EMPLOYEES = "EMPLOYEES",
	STORAGE = "STORAGE",

	RESEARCH = "RESEARCH",

	MAP = "MAP",

	EXPLORATION = "EXPLORE",

	COMPLEX = "COMPLEX",
	STATS = "STATS",
}
