export enum GameTabType {
	HOME = "YOUR HOUSE",
	LETTERS = "LETTERS",
	SHOP = "SHOP",
	EMPLOYEES = "EMPLOYEES",
	STORAGE = "STORAGE",

	EXPLORATION = "EXPLORE",
	DEFENCE = "DEFEND",

	PRODUCTION = "PRODUCTION",
	STATS = "STATS",
}
